### ISSUE TITLE
PELoader detected by Windows Defender as ransomware

### ISSUE THREAD

**Issue by rudolfninja** [xBurnsed/PE-Crypter#4]
PELoader detected by Windows 10 (11) Defender as ransomware
Most likely it is because of base64 and (or) rc4 ecnryption/decryption. However I wasn't able to get rid of it even after I commenred encryption functions

**Comment by xBurnsed** [comment]
This source code has been public for more than 5 years already or so. I wouldn't expect that it remained undetected this whole time, honestly.

**Comment by rudolfninja** [comment]
The problem was in `checkLoadDLL` function

**Comment by xBurnsed** [comment]
Wdym? You made it FUD scantime again?
It's prob gonna be detected runtime as of now tho.. AVs have upgraded a lot lately with all these new AI stuff going on

**Comment by rudolfninja** [comment]
> Wdym? You made it FUD scantime again? It's prob gonna be detected runtime as of now tho.. AVs have upgraded a lot lately with all these new AI stuff going on
First I commented the function and all checks on avcheck.net were green (passed). Then I uncommented the function, obfuscated lib names and unwind loops, and everything was fine after
